# -*- coding: utf-8 -*-
"""WEEK10LAB.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1a4szeQPEkCpJA0XLElM8SpaBFQQu0LW9
"""

Continous probability distribution Lab

import numpy as np
from scipy import stats
import math as mt
import random as rnd
import math

A = stats.norm(3,math.sqrt(16)) # Declare A to be a normal random variable
print(A.pdf(4))                 # f(4), the probability density at 4
print(A.cdf(2))                # f(2)



QUESTION 1 SOLUTION

import numpy as np
from scipy import stats
import math as mt
import random as rnd
import math

A = stats.norm(9,math.sqrt(64)) # Declare A to be a normal random variable
print(A.pdf(6))                 # f(4), the probability density at 6
print(A.cdf(6))                # f(2)

QUESTION 2 SOLUTION

import numpy as np
from scipy import stats
import math as mt
import random as rnd
import math

A = stats.norm(10,math.sqrt(2)) # Declare A to be a normal random variable
print(A.pdf(11))



Exponential Distribution

from scipy.stats import expon

# calculate probability that x is less than 50 when mean rate is 40

expon.cdf(x=50, scale=40)



QUESTION 3 SOLUTION

from scipy.stats import expon

# average of 20 orders per hour. To find probability that in just two minutes the pizzeria will receive an order.
# x=20, prob=2

expon.cdf(x=20, scale=2)